name: CI
on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: changeme
  schedule:
    - cron:  '0 * * * *'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: ./gradlew -v
    - name: ci
      run: |
        ./gradlew nativeImage
        ./build/graal/uname-graal
